// <auto-generated />
namespace TemplateBuilder.Infrastructure.EF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddGovernance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGovernance));
        
        string IMigrationMetadata.Id
        {
            get { return "202608192146468_AddGovernance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
